blank_issues_enabled: false
contact_links:
  - name: 💬 Discusiones del Proyecto
    url: https://github.com/Jorgez-tech/baloncestoteam/discussions
    about: Para discusiones generales sobre el proyecto
  - name: 📚 Documentación
    url: https://github.com/Jorgez-tech/baloncestoteam/blob/main/README.md
    about: Consulta la documentación del proyecto
